version: 2

models:
  - name: stg_tpch_customers
    description: staging layer for customers data
    columns:
      - name: customer_id
        description: this is the primary key for customers
        tests:
          - unique
          - not_null
      - name: customer_name
        description: name of the customer
      - name: nation_id
        description: foreign id to stg_tpch_nations
      - name: address
        description: address of the customer
      - name: phone_number
        description: phone number of the customer
      - name: account_balance
        description: account_balance of the customer
      - name: market_segment
        description: market segment of the customer
      - name: comment
        description: '{{ doc("comment") }}'

  - name: stg_tpch_line_items
    description: staging layer for line items data
    columns:
      - name: order_item_id
        description: surrogate key for the model -- combo of order_id + line_number
        tests:
          - unique
          - not_null        
      - name: order_id
        description: foreign id to stg_tpch_orders
      - name: part_id
        description: foreign id to stg_tpch_part_suppliers
      - name: supplier_id
        description: foreign id to stg_tpch_suppliers
      - name: line_number
        description: sequence of order items within the order
      - name: quantity
        description: total units of order items
      - name: extended_price
        description: price of order items
      - name: discount_percentage
        description: percentage of the discount
      - name: tax_rate
        description: tax rate of order item
      - name: return_flag
        description: letter determining the status of the return
      - name: order_item_status_code
        description: status code of the order item
      - name: ship_date
        description: the date the order item is being shipped
      - name: commit_date
        description: the date the order item is being commited
      - name: receipt_date
        description: the receipt date of the order item
      - name: ship_instructions
        description: additional instructions on the shipment
      - name: ship_mode
        description: method of shipping
      - name: comment
        description: '{{ doc("comment") }}'

  - name: stg_tpch_nations
    description: staging layer for nations data
    columns:
        - name: nation_id
          description: this is the primary key for nations data
          tests:
            - unique
            - not_null  
        - name: region_id
          description: foreign id to stg_tpch_regions
        - name: nation
          description: name of the nation
        - name: nation_comment
          description: '{{ doc("comment") }}'

  - name: stg_tpch_orders
    description: staging layer for orders data
    columns:
      - name: order_id
        description: this is the primary key for orders data
        tests:
          - unique
          - not_null 
      - name: customer_id
        description: foreign id to stg_tpch_customers
      - name: order_status_code
        description: status of the order      
      - name: total_price
        description: total price of order
      - name: order_date
        description: date the order was made
      - name: priority_code
        description: code associated with the order
      - name: clerk_name
        description: id of the clerk associated with the order
      - name: ship_priority
        description: numeric representation of the shipping priority, zero being the default
      - name: comment
        description: '{{ doc("comment") }}'

  - name: stg_tpch_part_suppliers
    description: staging layer for part by supplier data
    columns:
      - name: part_supplier_id
        description: surrogate id for the model -- combo of ps_partid + ps_suppid
        tests:
          - unique
          - not_null 
      - name: part_id
        description: foreign id to stg_tpch_parts
      - name: supplier_id
        description: foreign id to stg_tpch_suppliers
      - name: available_quantity
        description: raw available quantity of part by supplier
      - name: cost
        description: raw cost of part by supplier     
      - name: comment
        description: '{{ doc("comment") }}'     

  - name: stg_tpch_parts
    description: staging layer for parts data
    columns:
      - name: part_id
        description: this is the primary key for parts data
        tests:
          - unique
          - not_null         
      - name: part_name
        description: name of the part
      - name: manufacturer
        description: manufacturer of the part
      - name: brand
        description: brand of the part
      - name: part_type
        description: type of part including material
      - name: part_size
        description: size of the part
      - name: container
        description: container of the part
      - name: retail_price
        description: raw retail price    
      - name: comment
        description: '{{ doc("comment") }}'     

  - name: stg_tpch_regions
    description: staging layer for regions data
    columns:
      - name: region_id
        description: this is the primary key for nations data
        tests:
          - unique
          - not_null          
      - name: region
        description: name of region
      - name: region_comment
        description: '{{ doc("comment") }}' 

  - name: stg_tpch_suppliers
    config:
        materialized: ephemeral
    description: staging layer for suppliers data
    columns:
      - name: supplier_id
        description: this is the primary key for supplier data
        tests:
          - unique
          - not_null   
      - name: nation_id
        description: foreign id to stg_tpch_nations
      - name: supplier_name
        description: id of the supplier
      - name: supplier_address
        description: address of the supplier
      - name: phone_number
        description: phone number of the supplier
      - name: account_balance
        description: raw account balance
      - name: comment
        description: '{{ doc("comment") }}'         
